### ISSUE TITLE
item disappear from armor & inventory

### ISSUE THREAD

**Issue by fabienwang** [stujones11/minetest-3d_armor#36]
Hello,

I have experienced an horrible bug.

If by error you drop a second item ie. a black mitril shield 
but you already have a shield on the armor.
The new item will disappear, even from your inventory.

I think it would be better not to accept the new item if there is already one (cancel the drop & put back the item in the inventory?)

**Comment by stujones11** [comment]
That sounds more like a glitch in the engine since there is no code in the mod that would do that.
I have so far been unable to reproduce it, what version of minetest are you using?
The reason for allowing multiples of equipped items was originally so that the 'spare' slot could be used as a backup for an item perhaps due to expire. I might look at restricting it to single items in future, however.

**Comment by fabienwang** [comment]
You were right. It is a glitch in the core engine.
I was using a 0.4.13-dev so maybe it's fixed in the stable.

On our server we applied the same fix you suggest.

https://github.com/MinetestForFun/server-minetestforfun/commit/f5e8bc08b7a749c6ddab4a814ec3059ddf5faabe

Without any problem coming from your code, you may close this issue

**Comment by stujones11** [comment]
Thanks for the update.

**Comment by LeMagnesium** [comment]
No, it was not fixed, it's an engine problem, here's the way to reproduce it :
 - Take a piece of armor called A, put it in an inventory's slot called 'a'.
 - Take a second piece called B, put it in an inventory's slot called 'b'.
 - Once put in armor's inventory, take again the piece B, and click the piece A. You will get the piece A, and put the B in the slot 'a'.
 - Wait a few seconds, and the piece you grabbed will vanish

It's caused by the engine's behavior with inventories, but I'm not sure if we can avoid it.

**Comment by LeMagnesium** [comment]
https://github.com/MinetestForFun/server-minetestforfun/commit/0b2f6d8453cb55a547c70a947accfe8afd8965fb

We have news on this issue. It seems that somehow @crabman77 was able to fix it without touching the engine. Here is the commit he applied on our repository. If you are able to see what was wrong in that piece of code and maybe if we did a huge mistake changing that, please tell us.
